dateofbirth(napoleonbonaparte,"15august1769").
partof(revolutionarywars,"frenchrevolution").
haspart(frenchrevolution,"revolutionarywars").
partof(frenchrevolution,"revolutionarywars").
haspart(revolutionarywars,"frenchrevolution").
country(firstconsul,"frenchrepublic").
headofstate(frenchrepublic,"napoleon").
legislativebody(frenchrepublic,"firstconsul").
positionheld(napoleonbonaparte,"emperorofthefrench").
officeholder(emperorofthefrench,"napoleonbonaparte").
pointintime(1815,"1815").
occupation(napoleon,"political").
conflict(napoleon,"political").
dateofdeath(napoleonbonaparte,"15may1821").
dateofdeath(bonaparte,"15may1821").
pointintime(diedon15may1821,"15may1821").
